---
  - name: Generate directory structure
    hosts: DC1, DC2
    tasks:
    - name: Create a directory if it doesn't exist
      file:
        path: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}"
        state: directory

  - name: Generate interface EOS syntax
    hosts: DC1, DC2
    tasks:
    - name: Register variables into dictionary
      include_vars:
        file: "{{lookup('env','PWD')}}/vars/underlay.yml"
        name: underlay
    - name: Create interface configuration files
      template:
        src: "{{lookup('env','PWD')}}/templates/interfaces.j2"
        dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}/{{inventory_hostname}}_interfaces.cfg"

  - name: Generate leaf EVPN configuration
    hosts: leafs_DC1, leafs_DC2
    tasks:
    - name: Register variables into dictionary
      include_vars:
        file: "{{lookup('env','PWD')}}/vars/underlay.yml"
        name: underlay
    - name: Create leaf EVPN configuration files
      template:
        src: "{{lookup('env','PWD')}}/templates/leafs_EVPN.j2"
        dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}/{{inventory_hostname}}_EVPN.cfg"

  - name: Generate spine EVPN configuration
    hosts: spines_DC1, spines_DC2
    tasks:
    - name: Register variables into dictionary
      include_vars:
        file: "{{lookup('env','PWD')}}/vars/underlay.yml"
        name: underlay
    - name: Create leaf EVPN configuration files
      template:
        src: "{{lookup('env','PWD')}}/templates/spines_EVPN.j2"
        dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}/{{inventory_hostname}}_EVPN.cfg"


  - name: Generate VXLAN Tenant
    hosts: leafs_DC1, leafs_DC2
    tags: VXLAN
    tasks:
    - name: Register variables into dictionary
      include_vars:
        file: "{{lookup('env','PWD')}}/vars/underlay.yml"
        name: underlay
    - name: Register Tenant variables into dictionary
      include_vars:
        file: "{{lookup('env','PWD')}}/vars/VXLAN.yml"
        name: VXLAN
    - name: Create leaf EVPN configuration files
      template:
        src: "{{lookup('env','PWD')}}/templates/VXLAN_Tenant.j2"
        dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}/{{inventory_hostname}}_VXLAN.cfg"