---
  - name: Uploading configs to switches
    hosts: DC1, DC2
    tasks:
    - name: Upload interface configuration files
      arista.eos.eos_config:
        src: "{{lookup('env','PWD')}}/configs/final/{{inventory_hostname}}_final.cfg"
        save_when: always
        replace: config